import logging
import os
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------

# Configure structured logging so that EDA progress, warnings,
# and errors are visible when the script runs.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s"
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# EDA configuration
# ---------------------------------------------------------------------------

# Processed metadata generated by the image metadata pipeline.
METADATA_PATH = "data/processed/image_metadata.csv"

# Directory where generated visualisations are stored.
FIGURES_DIRECTORY = Path("reports/figures")

# Output paths for the generated figures.
BRIGHTNESS_FIGURE_PATH = (
    FIGURES_DIRECTORY / "brightness_distribution.png"
)

BLUR_FIGURE_PATH = (
    FIGURES_DIRECTORY / "blur_scores.png"
)

# Blur threshold used by the image metadata quality checks.
BLUR_THRESHOLD = 100


def load_metadata():
    """
    Load processed image metadata from the CSV file.

    Returns:
        pandas.DataFrame: Image metadata used for exploratory analysis.
    """

    logger.info(
        "Loading image metadata from %s.",
        METADATA_PATH
    )

    try:
        metadata_df = pd.read_csv(
            METADATA_PATH
        )

        logger.info(
            "Image metadata loaded successfully."
        )

        logger.info(
            "Dataset contains %d row(s) and %d column(s).",
            metadata_df.shape[0],
            metadata_df.shape[1]
        )

        return metadata_df

    except FileNotFoundError:
        logger.error(
            "Image metadata file was not found: %s",
            METADATA_PATH
        )

        return None

    except pd.errors.EmptyDataError:
        logger.error(
            "Image metadata file is empty: %s",
            METADATA_PATH
        )

        return None

    except Exception:
        logger.exception(
            "Unexpected error while loading image metadata."
        )

        return None


def display_dataset_summary(metadata_df):
    """
    Display basic dataset information and numerical statistics.

    The summary helps inspect the size, structure, and distribution
    of important image metadata fields.
    """

    logger.info(
        "Generating image dataset summary."
    )

    # Display the first few records so the processed data can
    # be inspected quickly.
    print("\nImage metadata preview:")
    print(metadata_df.head())

    # Display the number of rows and columns.
    print("\nDataset shape:")
    print(metadata_df.shape)

    # Generate descriptive statistics for important numerical fields.
    numerical_columns = [
        "width",
        "height",
        "file_size_bytes",
        "brightness",
        "blur_score",
    ]

    print("\nNumerical summary:")
    print(
        metadata_df[
            numerical_columns
        ].describe()
    )

    # Display counts for each brightness quality category.
    print("\nBrightness quality:")
    print(
        metadata_df[
            "brightness_warning"
        ].value_counts()
    )

    # Display counts for each blur quality category.
    print("\nBlur quality:")
    print(
        metadata_df[
            "blur_warning"
        ].value_counts()
    )

    logger.info(
        "Dataset summary generated successfully."
    )


def create_brightness_distribution(metadata_df):
    """
    Create a histogram showing image brightness distribution.

    The histogram helps identify whether the dataset contains
    unusually dark or bright images.
    """

    logger.info(
        "Creating brightness distribution figure."
    )

    try:
        # Create a new figure so plots remain independent.
        plt.figure()

        # Plot the distribution of calculated image brightness values.
        plt.hist(
            metadata_df["brightness"],
            bins=5
        )

        plt.title(
            "Image Brightness Distribution"
        )

        plt.xlabel(
            "Brightness"
        )

        plt.ylabel(
            "Number of Images"
        )

        plt.tight_layout()

        # Save the figure so it can be included in reports
        # and reviewed without rerunning the script.
        plt.savefig(
            BRIGHTNESS_FIGURE_PATH
        )

        logger.info(
            "Brightness distribution saved to %s.",
            BRIGHTNESS_FIGURE_PATH
        )

        plt.show()

        # Close the figure to release Matplotlib resources.
        plt.close()

    except Exception:
        logger.exception(
            "Failed to create brightness distribution figure."
        )


def create_blur_scores_chart(metadata_df):
    """
    Create a bar chart showing the blur score for each image.

    The horizontal threshold line shows the blur cutoff used by
    the image quality validation logic.
    """

    logger.info(
        "Creating image blur score figure."
    )

    try:
        # Extract only the filename from each complete file path
        # so the x-axis labels remain readable.
        image_names = metadata_df[
            "file_path"
        ].apply(
            os.path.basename
        )

        # Create a separate figure for blur analysis.
        plt.figure()

        plt.bar(
            image_names,
            metadata_df["blur_score"]
        )

        plt.title(
            "Image Blur Scores"
        )

        plt.xlabel(
            "Image"
        )

        plt.ylabel(
            "Laplacian Variance"
        )

        # Display the same blur threshold used by the metadata
        # extraction pipeline.
        plt.axhline(
            y=BLUR_THRESHOLD,
            linestyle="--",
            label="Blur threshold"
        )

        plt.legend()

        # Rotate filenames to prevent overlapping labels.
        plt.xticks(
            rotation=45,
            ha="right"
        )

        plt.tight_layout()

        # Save the generated visualisation for reporting.
        plt.savefig(
            BLUR_FIGURE_PATH
        )

        logger.info(
            "Blur score figure saved to %s.",
            BLUR_FIGURE_PATH
        )

        plt.show()

        # Close the figure after displaying it.
        plt.close()

    except Exception:
        logger.exception(
            "Failed to create blur score figure."
        )


def run_image_eda():
    """
    Run exploratory data analysis on processed image metadata.

    The workflow loads the metadata, displays descriptive statistics,
    analyses image-quality categories, and produces visual reports.
    """

    logger.info(
        "Starting SentinelVision image EDA."
    )

    # Ensure the figure output directory exists before saving plots.
    FIGURES_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True
    )

    # Load the processed metadata.
    metadata_df = load_metadata()

    if metadata_df is None:
        logger.error(
            "Image EDA stopped because metadata could not be loaded."
        )

        return

    if metadata_df.empty:
        logger.warning(
            "Image EDA stopped because the dataset contains no records."
        )

        return

    # Generate descriptive statistics and quality summaries.
    display_dataset_summary(
        metadata_df
    )

    # Generate brightness and blur visualisations.
    create_brightness_distribution(
        metadata_df
    )

    create_blur_scores_chart(
        metadata_df
    )

    logger.info(
        "SentinelVision image EDA completed successfully."
    )


if __name__ == "__main__":
    run_image_eda()
    