import logging

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError


# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------

# Configure logging so that pipeline progress and errors are visible
# when the script runs.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s"
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Database configuration
# ---------------------------------------------------------------------------

# Create a connection engine for the local SentinelVision PostgreSQL database.
engine = create_engine(
    "postgresql+psycopg2://krishnakanthmohanraj@localhost:5432/sentinelvision"
)

# Processed video metadata generated by the video metadata ETL pipeline.
METADATA_PATH = "data/processed/video_metadata.csv"

# PostgreSQL table used to store video metadata.
TABLE_NAME = "video_metadata"


def load_video_metadata():
    """
    Load processed video metadata into PostgreSQL.

    Existing videos are identified using their SHA-256 hashes so that
    running the loader multiple times does not create duplicate records.
    """

    try:
        # -------------------------------------------------------------------
        # Step 1: Read processed video metadata
        # -------------------------------------------------------------------

        logger.info(
            "Reading video metadata from %s.",
            METADATA_PATH
        )

        metadata_df = pd.read_csv(METADATA_PATH)

        logger.info(
            "Total videos processed: %d",
            len(metadata_df)
        )

        # -------------------------------------------------------------------
        # Step 2: Retrieve hashes already stored in PostgreSQL
        # -------------------------------------------------------------------

        logger.info(
            "Checking existing video hashes in PostgreSQL."
        )

        with engine.connect() as connection:
            existing_hashes = pd.read_sql(
                text(
                    """
                    SELECT sha256
                    FROM video_metadata
                    WHERE sha256 IS NOT NULL
                    """
                ),
                connection
            )

        # Convert the database hashes to a set for efficient membership checks.
        existing_hashes_set = set(
            existing_hashes["sha256"]
        )

        logger.info(
            "Existing video hashes in database: %d",
            len(existing_hashes_set)
        )

        # -------------------------------------------------------------------
        # Step 3: Filter out videos already stored in PostgreSQL
        # -------------------------------------------------------------------

        new_metadata_df = metadata_df[
            ~metadata_df["sha256"].isin(
                existing_hashes_set
            )
        ]

        logger.info(
            "New videos to insert: %d",
            len(new_metadata_df)
        )

        # -------------------------------------------------------------------
        # Step 4: Insert only new video metadata
        # -------------------------------------------------------------------

        if not new_metadata_df.empty:
            logger.info(
                "Inserting new video metadata into PostgreSQL."
            )

            new_metadata_df.to_sql(
                TABLE_NAME,
                engine,
                if_exists="append",
                index=False
            )

            logger.info(
                "%d new video record(s) inserted successfully.",
                len(new_metadata_df)
            )

        else:
            logger.info(
                "No new videos to insert."
            )

        logger.info(
            "Video metadata database load completed successfully."
        )

    except FileNotFoundError:
        logger.error(
            "Video metadata file was not found: %s",
            METADATA_PATH
        )

    except pd.errors.EmptyDataError:
        logger.error(
            "Video metadata file is empty: %s",
            METADATA_PATH
        )

    except SQLAlchemyError:
        logger.exception(
            "A PostgreSQL database error occurred while loading video metadata."
        )

    except Exception:
        logger.exception(
            "An unexpected error occurred while loading video metadata."
        )


if __name__ == "__main__":
    load_video_metadata()
    