import logging

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError


# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------

# Configure structured logging so that pipeline progress and errors
# are clearly visible when the script runs.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s"
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Database configuration
# ---------------------------------------------------------------------------

# Create a connection engine for the local SentinelVision PostgreSQL database.
engine = create_engine(
    "postgresql+psycopg2://krishnakanthmohanraj@localhost:5432/sentinelvision"
)

# Processed image metadata generated by the image metadata ETL pipeline.
METADATA_PATH = "data/processed/image_metadata.csv"

# PostgreSQL table used to store image metadata.
TABLE_NAME = "image_metadata"


def load_image_metadata():
    """
    Load processed image metadata into PostgreSQL.

    Existing images are identified using their SHA-256 hashes so that
    running the loader multiple times does not create duplicate records.
    """

    try:
        # -------------------------------------------------------------------
        # Step 1: Read processed image metadata
        # -------------------------------------------------------------------

        logger.info(
            "Reading image metadata from %s.",
            METADATA_PATH
        )

        metadata_df = pd.read_csv(METADATA_PATH)

        logger.info(
            "Total images processed: %d",
            len(metadata_df)
        )

        # -------------------------------------------------------------------
        # Step 2: Retrieve hashes already stored in PostgreSQL
        # -------------------------------------------------------------------

        logger.info(
            "Checking existing image hashes in PostgreSQL."
        )

        with engine.connect() as connection:
            existing_hashes = pd.read_sql(
                text(
                    """
                    SELECT sha256
                    FROM image_metadata
                    WHERE sha256 IS NOT NULL
                    """
                ),
                connection
            )

        # Convert existing database hashes to a set for efficient lookup.
        existing_hashes_set = set(
            existing_hashes["sha256"]
        )

        logger.info(
            "Existing image hashes in database: %d",
            len(existing_hashes_set)
        )

        # -------------------------------------------------------------------
        # Step 3: Filter out images already stored in PostgreSQL
        # -------------------------------------------------------------------

        new_metadata_df = metadata_df[
            ~metadata_df["sha256"].isin(
                existing_hashes_set
            )
        ]

        logger.info(
            "New images to insert: %d",
            len(new_metadata_df)
        )

        # -------------------------------------------------------------------
        # Step 4: Insert only new image metadata
        # -------------------------------------------------------------------

        if not new_metadata_df.empty:
            logger.info(
                "Inserting new image metadata into PostgreSQL."
            )

            new_metadata_df.to_sql(
                TABLE_NAME,
                engine,
                if_exists="append",
                index=False
            )

            logger.info(
                "%d new image record(s) inserted successfully.",
                len(new_metadata_df)
            )

        else:
            logger.info(
                "No new images to insert."
            )

        logger.info(
            "Image metadata database load completed successfully."
        )

    except FileNotFoundError:
        logger.error(
            "Image metadata file was not found: %s",
            METADATA_PATH
        )

    except pd.errors.EmptyDataError:
        logger.error(
            "Image metadata file is empty: %s",
            METADATA_PATH
        )

    except SQLAlchemyError:
        logger.exception(
            "A PostgreSQL database error occurred while loading image metadata."
        )

    except Exception:
        logger.exception(
            "An unexpected error occurred while loading image metadata."
        )


if __name__ == "__main__":
    load_image_metadata()
    